### ISSUE TITLE
ErrorException with message 'Class 'App\Services\RemoteService' not found'

### ISSUE THREAD

**Issue by andersondeoliveiramachado** [HexPang/laravel-ssh#7]
php artisan tinker
use SSH;

$host = "192.168.0.2";
$port = "22";
$username = "noc";
$password = "noc";
$command = "grep ppp.1.name= /tmp/system.cfg";

$ssh = new SSH($host,$port,$username,$password);

ErrorException with message 'Class 'App\Services\RemoteService' not found'

**Comment by HexPang** [comment]
Sorry,my mistake.
Try this namespace

> hexpang\Services\SSHService

**Comment by andersondeoliveiramachado** [comment]
Solved !

Putting 

'SSH' => hexpang\Services\SSHService::class, 

in config / app.php
